# Software and Platforms {#sec-software-and-platforms .unnumbered}

## Download/Sign Up Links {#sec-download-sign-up-links}

+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| Software/Platform        | Purpose                                                                         | Download/Sign Up Link                                                                                       |
+==========================+=================================================================================+=============================================================================================================+
| Slack                    | Enhances team communication and project coordination                            | [Windows Link](https://slack.com/intl/en-in/downloads/windows)                                              |
|                          |                                                                                 |                                                                                                             |
|                          |                                                                                 | [Mac Link](https://slack.com/intl/en-in/downloads/mac)                                                      |
+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| Google Drive for Desktop | Streamlines file storage, sharing, and collaboration                            | [Link](https://www.google.com/drive/download/)                                                              |
+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| R                        | Provides tools for statistical analysis and data visualization                  | [Link](https://cran.rstudio.com/)                                                                           |
+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| RStudio                  | Facilitates R coding, debugging, and project organization                       | [Link](https://posit.co/download/rstudio-desktop/)                                                          |
+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| Git                      | Manages version control for tracking and merging changes in code and documents  | [Link](https://git-scm.com/downloads)                                                                       |
+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| GitHub                   | Hosts and manages Git repositories, facilitating collaboration and code sharing | [Link](https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home) |
+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| Zotero                   | Organizes and cites research sources consistently                               | [Link](https://www.zotero.org/download/)                                                                    |
+--------------------------+---------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+

## Setup Instructions